# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aff0ca00dcb3a3cd54ed4de86ace697be5981c99f4fb50a201cb60f855746bc729f06447e849481ffcf2ed0df69e796efdc353c30d37f5ec9f57b76a16ea782

test:
  secret_key_base: 004998acb809c7d073b534de03c83f14b005ddb2b65490fdf52851ce252251576809f92bd1dae2e5b2862e72f91579bc5532d6ddd8340c5e73cfb90ea58cfad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
